const TOUR_STEP_PROFILES = 0
const TOUR_STEP_ADD = 1
const TOUR_STEP_PLAY = 2
const TOUR_STEP_MODS = 3
const TOUR_STEP_PROBLEMS = 4
const TOUR_STEP_COMMAND = 5

export {
  TOUR_STEP_ADD,
  TOUR_STEP_COMMAND,
  TOUR_STEP_MODS,
  TOUR_STEP_PLAY,
  TOUR_STEP_PROBLEMS,
  TOUR_STEP_PROFILES,
}
