import { msg } from '@lingui/core/macro'
import { create } from 'zustand'
import type { Settings } from '../../bindings/github.com/Rethunk-Tech/mortar/internal/settings/models.ts'
import {
  CorruptSettingsPath,
  Get,
  ShowCorruptSettings,
} from '../../bindings/github.com/Rethunk-Tech/mortar/internal/settings/service.ts'
import { i18n } from '../i18n/index.ts'
import { follow } from '../shell/follow.ts'
import { reportUnexpected } from '../toasts/report.ts'
import { useToasts } from '../toasts/store.ts'

const defaults: Settings = {
  language: '',
  accent: 'sand',
  background: 'image',
  backgroundImage: '',
  lastGame: '',
  lastProfile: {},
  lastPlayed: {},
  gameFolders: {},
  gameStores: {},
  launcherRoots: {},
  launchersConfirmed: false,
  loaders: {},
  dismissed: {},
  nexusUserId: 0,
  nexusName: '',
  nexusPremium: false,
  nxmHandled: false,
  nxmPreviousHandlers: {},
  nxmPreviousName: '',
  nxmAsked: false,
  nxmRedirectOtherGames: null,
  nexusPreferredDownloadServer: '',
  nexusSeenDownloadServers: [],
  checkModUpdatesOnStart: true,
  tellWhenSmapiOut: true,
  askEndorseMods: true,
  keepInTray: false,
  lanSharing: false,
  lanPort: 47_630,
  lanAddresses: [],
  includeBetaReleases: false,
  includePrereleaseModVersions: false,
  checkOnlyEnabledMods: false,
  enableModsWhenInstalled: true,
  listColumns: [
    'on',
    'name',
    'version',
    'author',
    'source',
    'category',
    'status',
    'size',
    'startup',
  ],
  listSortColumn: 'name',
  listSortDir: 'asc',
  listGroupBy: 'status',
  tipsSeen: [],
  smapiToastAt: '',
  overlayEnabled: false,
  overlayPort: 8123,
  overlayToken: '',
  shortcuts: {},
  onPlay: 'stay',
  games: {},
  parallelDownloads: 3,
  updateCheckIntervalMinutes: 60,
  notifyModUpdates: false,
  updateDigest: 'daily',
  lastModUpdateDigest: [],
  lastModUpdateDigestAt: '',
  keepDownloadArchives: false,
  storeRetentionDays: 30,
  defaultModsView: 'grid',
  confirmRemovals: true,
  backgroundBadgeChecks: true,
  startScreen: 'last',
  dates: 'relative',
  trashRetentionDays: 30,
  historyEventsKept: 200,
  notifyDownloadFinished: true,
  notifyDownloadFailed: true,
  notifyRunCrashed: true,
  desktopDownloadFinished: false,
  desktopDownloadFailed: true,
  desktopRunCrashed: true,
  desktopModUpdates: false,
  density: 'comfortable',
  theme: 'dark',
  gridCardSize: 'medium',
  showAuthorOnCards: true,
  reduceMotion: 'system',
  profileHero: 'full',
  reuseFomodChoices: true,
  driftChecks: true,
  autoInstallMortarUpdates: true,
  autoTrackNexus: false,
  lanName: '',
  lanAutoAcceptSameAccount: false,
  downloadFolder: '',
  profileOrder: 'manual',
  autoRetryDownloads: 'off',
  pauseDownloadsWhilePlaying: false,
  sidebarBadges: 'problemsAndUpdates',
  shareIncludeDisabledMods: false,
  shareIncludeFomodChoices: true,
  shareIncludeNotes: true,
  shareIncludeConfigFiles: true,
  verifyNexusMD5: false,
  launchAtLogin: false,
  startMinimised: false,
  rememberWindow: false,
  extensionConnection: 'allow',
} as Settings

export const useSettings = create<Settings>(() => defaults)

export const initSettings = async () => {
  await follow('settings:changed', Get, (next) => useSettings.setState(next))
  const path = await CorruptSettingsPath()
  if (path) {
    useToasts.getState().push({
      kind: 'warning',
      title: i18n._(msg`Your settings could not be read`),
      body: i18n._(
        msg`Mortar started with default settings. The damaged file was kept at ${path}.`,
      ),
      action: {
        label: i18n._(msg`Show file`),
        run: () => ShowCorruptSettings().catch(reportUnexpected),
      },
    })
  }
}
