import { create } from 'zustand'
import type { Settings } from '../../bindings/github.com/Rethunk-AI/mortar/internal/settings/models.ts'
import {
  CorruptSettingsPath,
  Get,
} from '../../bindings/github.com/Rethunk-AI/mortar/internal/settings/service.ts'
import { follow } from '../shell/follow.ts'
import { useToasts } from '../toasts/store.ts'

const defaults: Settings = {
  language: '',
  accent: 'sand',
  background: 'image',
  backgroundImage: '',
  lastGame: '',
  lastProfile: {},
  lastPlayed: {},
  gameFolders: {},
  gameStores: {},
  launcherRoots: {},
  launchersConfirmed: false,
  loaders: {},
  dismissed: {},
  nexusUserId: 0,
  nexusName: '',
  nexusPremium: false,
  nxmHandled: false,
  nxmPrevious: '',
  nxmPreviousName: '',
  nxmAsked: false,
  nxmRedirectOtherGames: null,
  nexusPreferredDownloadServer: '',
  nexusSeenDownloadServers: [],
  checkModUpdatesOnStart: true,
  tellWhenSmapiOut: true,
  askEndorseMods: true,
  keepInTray: false,
  lanSharing: false,
  lanPort: 47_630,
  lanAddresses: [],
  includeBetaReleases: false,
  includePrereleaseModVersions: false,
  checkOnlyEnabledMods: false,
  enableModsWhenInstalled: true,
  backupsKept: 5,
  listColumns: ['on', 'name', 'version', 'author', 'source', 'category', 'status', 'size'],
  listSortColumn: 'name',
  listSortDir: 'asc',
  listGroupBy: 'status',
  tipsSeen: [],
  smapiToastAt: '',
  overlayEnabled: false,
  overlayPort: 8123,
  overlayToken: '',
  shortcuts: {},
  onPlay: 'stay',
  games: {
    stardew: {
      backupBeforePlay: 'changed',
      launchBackupsKept: 5,
      updateModsBeforePlayDefault: false,
      skipPlayCheck: false,
      runsKept: 20,
      consoleLogCap: 20_000,
      watchDownloads: true,
      nxmDefaultProfile: '',
      cosmeticConflicts: 'collapsed',
      enableRequirements: 'always',
      missingRequirements: 'ask',
      smapiBuilds: 'show',
      smapiPin: '',
      defaultLaunchMethod: 'steam',
      showSmapiConsole: true,
      consoleLevel: 'info',
      consoleTimestamps: true,
      consoleFollow: true,
      backupLocation: '',
      conflictScanDepth: 'full',
    },
  },
  parallelDownloads: 3,
  updateCheckIntervalMinutes: 60,
  notifyModUpdates: false,
  updateDigest: 'daily',
  lastModUpdateDigest: [],
  lastModUpdateDigestAt: '',
  keepDownloadArchives: false,
  storeRetentionDays: 30,
  defaultModsView: 'grid',
  confirmRemovals: true,
  backgroundBadgeChecks: true,
  startScreen: 'last',
  dates: 'relative',
  trashRetentionDays: 30,
  historyEventsKept: 200,
  notifyDownloadFinished: true,
  notifyDownloadFailed: true,
  notifyRunCrashed: true,
  density: 'comfortable',
  theme: 'dark',
  gridCardSize: 'medium',
  showAuthorOnCards: true,
  reduceMotion: 'system',
  profileHero: 'full',
  reuseFomodChoices: true,
  driftChecks: true,
  autoInstallMortarUpdates: true,
  autoTrackNexus: false,
  lanName: '',
  lanAutoAcceptSameAccount: false,
  downloadFolder: '',
  profileOrder: 'manual',
  autoRetryDownloads: 'off',
  pauseDownloadsWhilePlaying: false,
  sidebarBadges: 'problemsAndUpdates',
  shareIncludeDisabledMods: false,
  shareIncludeFomodChoices: true,
  shareIncludeNotes: true,
  shareIncludeConfigFiles: true,
  verifyNexusMD5: false,
  launchAtLogin: false,
  startMinimised: false,
  rememberWindow: false,
  extensionConnection: 'allow',
} as Settings

export const useSettings = create<Settings>(() => defaults)

export const initSettings = async () => {
  await follow('settings:changed', Get, (next) => useSettings.setState(next))
  const path = await CorruptSettingsPath()
  if (path) {
    useToasts.getState().push({
      kind: 'warning',
      title: 'Settings could not be read',
      body: `A copy was kept at ${path}`,
    })
  }
}
